# Generated by Django 4.1.2 on 2022-11-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_geography_product_roasting_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sour',
            field=models.CharField(blank=True, choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], max_length=30),
        ),
    ]
